## Experiment No : 1

## Title Linear Algebra 

**Name:** Himanshu Jadhav

**Roll Number:** SE-33

### 📌 Problem Statement

- Create a 3×3 matrix and compute its determinant.
- Find the inverse of the matrix.
- Solve a system of linear equations:
  - 2x + 3y = 10
  - 4x + 5y = 20


In [1]:
import numpy as np

In [2]:
A = np.array([
    [2,3,1],
    [4,5,6],
    [7,8,9]
])

In [3]:
print("Matix A: ")
print(A)

Matix A: 
[[2 3 1]
 [4 5 6]
 [7 8 9]]


In [4]:
det_A = np.linalg.det(A)
print(f"Determinant of arr: {det_A:.4f}")

Determinant of arr: 9.0000


In [5]:
if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("Inverse of A: ")
    print(np.round(inv_A, 4))

else:
    print("Matrix is Singular; inverse does not exist.")

Inverse of A: 
[[-0.3333 -2.1111  1.4444]
 [ 0.6667  1.2222 -0.8889]
 [-0.3333  0.5556 -0.2222]]


In [6]:
# Linear Equation: 2x + 3y = 10 & 4x + 5y = 20

coeff_matrix = np.array(
    [
        [2,3],
        [4,5]
    ]
)

const_vector = np.array(
    [10,20]
)

soln = np.linalg.solve(coeff_matrix, const_vector)


In [7]:
print(f"Solution: x = {soln[0]:.4f}, y = {soln[1]:.4f}")

Solution: x = 5.0000, y = 0.0000
